<?php

namespace ibanu\MainBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends DocumentRepository
{
}